-- Version 1. Run only in a NEW merchant schema in the dedicated hosting database.
-- No Supabase dependencies, shared public tables, demo customers or default credentials.

CREATE TABLE IF NOT EXISTS "tbl_advertisements" (
  "ad_id" SERIAL PRIMARY KEY,
  "advertiser_user_id" INTEGER NOT NULL,
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "ad_type" TEXT CHECK ("ad_type" IN ('banner','popup','featured_listing')) NOT NULL DEFAULT 'banner',
  "target_url" VARCHAR(255) DEFAULT NULL,
  "image_file" VARCHAR(255) DEFAULT NULL,
  "start_date" TIMESTAMPTZ NOT NULL,
  "end_date" TIMESTAMPTZ NOT NULL,
  "price_paid" NUMERIC(10, 2) DEFAULT NULL,
  "status" TEXT CHECK ("status" IN ('active','inactive','pending_approval','rejected','expired')) NOT NULL DEFAULT 'pending_approval',
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_auctions" (
  "auction_id" SERIAL PRIMARY KEY,
  "seller_user_id" INTEGER NOT NULL,
  "product_name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "starting_bid" NUMERIC(10, 2) NOT NULL,
  "current_bid" NUMERIC(10, 2) DEFAULT NULL,
  "highest_bidder_user_id" INTEGER DEFAULT NULL,
  "main_photo" VARCHAR(255) DEFAULT NULL,
  "other_photos" TEXT,
  "start_time" TIMESTAMPTZ NOT NULL,
  "end_time" TIMESTAMPTZ NOT NULL,
  "status" TEXT CHECK ("status" IN ('active','completed','cancelled','pending_approval','rejected')) NOT NULL DEFAULT 'pending_approval',
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_auction_bids" (
  "bid_id" SERIAL PRIMARY KEY,
  "auction_id" INTEGER NOT NULL,
  "bidder_user_id" INTEGER NOT NULL,
  "bid_amount" NUMERIC(10, 2) NOT NULL,
  "bid_time" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_businesses" (
  "business_id" SERIAL PRIMARY KEY,
  "owner_user_id" INTEGER NOT NULL,
  "business_name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "address" VARCHAR(255) NOT NULL,
  "city" VARCHAR(100) NOT NULL,
  "nid_number" VARCHAR(50) DEFAULT NULL,
  "nid_front_doc" VARCHAR(255) NOT NULL,
  "nid_back_doc" VARCHAR(255) NOT NULL,
  "nid_document" VARCHAR(255) DEFAULT NULL,
  "face_capture" VARCHAR(255) DEFAULT NULL,
  "state" VARCHAR(100) DEFAULT NULL,
  "zip" VARCHAR(20) DEFAULT NULL,
  "phone" VARCHAR(50) NOT NULL,
  "email" VARCHAR(255) DEFAULT NULL,
  "trade_license_number" VARCHAR(100) DEFAULT NULL,
  "trade_license_photo" VARCHAR(255) DEFAULT NULL,
  "tin_certificate_photo" VARCHAR(255) DEFAULT NULL,
  "other_organization_docs" TEXT,
  "website" VARCHAR(255) DEFAULT NULL,
  "latitude" NUMERIC(10, 8) DEFAULT NULL,
  "longitude" NUMERIC(11, 8) DEFAULT NULL,
  "logo" VARCHAR(255) DEFAULT NULL,
  "banner_photo" VARCHAR(255) DEFAULT NULL,
  "verification_status" TEXT CHECK ("verification_status" IN ('pending','approved','rejected')) NOT NULL DEFAULT 'pending',
  "is_active" SMALLINT NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_coin_transactions" (
  "transaction_id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "transaction_type" TEXT CHECK ("transaction_type" IN ('credit','debit')) NOT NULL,
  "amount" NUMERIC(15, 2) NOT NULL,
  "description" TEXT,
  "source_id" INTEGER DEFAULT NULL,
  "transaction_date" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_color" (
  "color_id" SERIAL PRIMARY KEY,
  "color_name" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_country" (
  "country_id" SERIAL PRIMARY KEY,
  "country_name" VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_coupon" (
  "coupon_id" SERIAL PRIMARY KEY,
  "coupon_code" VARCHAR(50) NOT NULL,
  "discount_type" TEXT CHECK ("discount_type" IN ('percentage','fixed')) NOT NULL DEFAULT 'percentage',
  "discount_value" NUMERIC(10, 2) NOT NULL,
  "minimum_order" NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  "usage_limit" INTEGER NOT NULL DEFAULT 0,
  "used_count" INTEGER NOT NULL DEFAULT 0,
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL,
  "status" TEXT CHECK ("status" IN ('active','inactive')) NOT NULL DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS "tbl_customer" (
  "cust_id" SERIAL PRIMARY KEY,
  "cust_name" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_cname" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_email" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_phone" VARCHAR(50) NOT NULL DEFAULT '',
  "cust_country" INTEGER NOT NULL DEFAULT 0,
  "cust_address" TEXT NOT NULL DEFAULT '',
  "cust_city" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_state" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_zip" VARCHAR(30) NOT NULL DEFAULT '',
  "cust_b_name" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_b_cname" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_b_phone" VARCHAR(50) NOT NULL DEFAULT '',
  "cust_b_country" INTEGER NOT NULL DEFAULT 0,
  "cust_b_address" TEXT NOT NULL DEFAULT '',
  "cust_b_city" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_b_state" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_b_zip" VARCHAR(30) NOT NULL DEFAULT '',
  "cust_s_name" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_s_cname" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_s_phone" VARCHAR(50) NOT NULL DEFAULT '',
  "cust_s_country" INTEGER NOT NULL DEFAULT 0,
  "cust_s_address" TEXT NOT NULL DEFAULT '',
  "cust_s_city" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_s_state" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_s_zip" VARCHAR(30) NOT NULL DEFAULT '',
  "cust_password" VARCHAR(255) NOT NULL DEFAULT '',
  "cust_coin_balance" NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  "cust_token" VARCHAR(255) NOT NULL DEFAULT '',
  "cust_datetime" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_timestamp" VARCHAR(100) NOT NULL DEFAULT '',
  "cust_status" SMALLINT NOT NULL DEFAULT 0,
  "role_type" VARCHAR(50) DEFAULT 'customer',
  "is_verified" SMALLINT DEFAULT 0,
  "trust_score" INTEGER DEFAULT 50,
  "current_lat" NUMERIC(10, 8) DEFAULT NULL,
  "current_lng" NUMERIC(11, 8) DEFAULT NULL,
  "wallet_balance" NUMERIC(15, 2) DEFAULT 0.00,
  "identity_doc_path" VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_customer_carts" (
  "cart_id" SERIAL PRIMARY KEY,
  "customer_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "size_id" INTEGER DEFAULT NULL,
  "size_name" VARCHAR(255),
  "color_id" INTEGER DEFAULT NULL,
  "color_name" VARCHAR(255),
  "quantity" INTEGER NOT NULL DEFAULT 1,
  "price_at_add" NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  "product_name" VARCHAR(255),
  "product_photo" VARCHAR(255) DEFAULT NULL,
  "added_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_customer_message" (
  "customer_message_id" SERIAL PRIMARY KEY,
  "subject" VARCHAR(255) NOT NULL,
  "message" TEXT NOT NULL,
  "order_detail" TEXT NOT NULL,
  "cust_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_drivers" (
  "driver_id" SERIAL PRIMARY KEY,
  "user_id" INTEGER DEFAULT NULL,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) DEFAULT NULL,
  "phone" VARCHAR(50) NOT NULL,
  "nid_number" VARCHAR(50) DEFAULT NULL,
  "nid_photo_front" VARCHAR(255) DEFAULT NULL,
  "nid_photo_back" VARCHAR(255) DEFAULT NULL,
  "driving_license_number" VARCHAR(100) DEFAULT NULL,
  "driving_license_photo" VARCHAR(255) DEFAULT NULL,
  "vehicle_registration_photo" VARCHAR(255) DEFAULT NULL,
  "license_number" VARCHAR(100) NOT NULL,
  "vehicle_type" TEXT CHECK ("vehicle_type" IN ('rickshaw','cng','bike','car')) NOT NULL,
  "current_latitude" NUMERIC(10, 8) DEFAULT NULL,
  "current_longitude" NUMERIC(11, 8) DEFAULT NULL,
  "status" TEXT CHECK ("status" IN ('online','offline','on_trip')) NOT NULL DEFAULT 'offline',
  "is_verified" SMALLINT NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_emergency_contacts" (
  "contact_id" SERIAL PRIMARY KEY,
  "service_type" VARCHAR(100) NOT NULL,
  "contact_number" VARCHAR(50) NOT NULL,
  "region" VARCHAR(255) DEFAULT NULL,
  "description" TEXT,
  "is_active" SMALLINT NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_end_category" (
  "ecat_id" SERIAL PRIMARY KEY,
  "ecat_name" VARCHAR(255) NOT NULL,
  "mcat_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_faq" (
  "faq_id" SERIAL PRIMARY KEY,
  "faq_title" VARCHAR(255) NOT NULL,
  "faq_content" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_features" (
  "id" SERIAL PRIMARY KEY,
  "icon" VARCHAR(50) NOT NULL,
  "title" VARCHAR(100) NOT NULL,
  "link" VARCHAR(255) NOT NULL,
  "order_no" INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "tbl_food_orders" (
  "order_id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "restaurant_id" INTEGER NOT NULL,
  "delivery_address" TEXT NOT NULL,
  "delivery_latitude" NUMERIC(10, 8) NOT NULL,
  "delivery_longitude" NUMERIC(11, 8) NOT NULL,
  "order_total" NUMERIC(10, 2) NOT NULL,
  "delivery_fee" NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  "payment_method" VARCHAR(50) NOT NULL,
  "payment_status" TEXT CHECK ("payment_status" IN ('pending','paid','refunded')) NOT NULL DEFAULT 'pending',
  "order_status" TEXT CHECK ("order_status" IN ('placed','accepted','preparing','out_for_delivery','delivered','cancelled')) NOT NULL DEFAULT 'placed',
  "driver_id" INTEGER DEFAULT NULL,
  "order_notes" TEXT,
  "placed_at" TIMESTAMPTZ DEFAULT NOW(),
  "accepted_at" TIMESTAMPTZ DEFAULT NULL,
  "delivered_at" TIMESTAMPTZ DEFAULT NULL,
  "cancelled_at" TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_food_order_items" (
  "order_item_id" SERIAL PRIMARY KEY,
  "order_id" INTEGER NOT NULL,
  "item_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "price_at_order" NUMERIC(10, 2) NOT NULL,
  "notes" TEXT
);

CREATE TABLE IF NOT EXISTS "tbl_gov_projects" (
  "project_id" SERIAL PRIMARY KEY,
  "project_name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "region" VARCHAR(255) NOT NULL,
  "start_date" DATE,
  "end_date" DATE,
  "status" TEXT CHECK ("status" IN ('planning','voting','approved','in_progress','completed','cancelled')) NOT NULL DEFAULT 'planning',
  "total_votes_for" INTEGER NOT NULL DEFAULT 0,
  "total_votes_against" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_home_sections" (
  "id" SERIAL PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "category_id" INTEGER NOT NULL,
  "category_type" VARCHAR(20) NOT NULL,
  "product_limit" INTEGER DEFAULT 8,
  "order_no" INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "tbl_home_tabs" (
  "id" SERIAL PRIMARY KEY,
  "tab_name" VARCHAR(100) NOT NULL,
  "tab_icon" VARCHAR(50) NOT NULL,
  "filter_type" TEXT CHECK ("filter_type" IN ('recommendation','free_shipping','top_sale','max_vouchered','overseas','premium','official')) NOT NULL,
  "display_order" INTEGER NOT NULL DEFAULT 0,
  "is_active" SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "tbl_hotels" (
  "hotel_id" SERIAL PRIMARY KEY,
  "owner_user_id" INTEGER DEFAULT NULL,
  "travel_agency_id" INTEGER DEFAULT NULL,
  "hotel_name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "address" VARCHAR(255) NOT NULL,
  "city" VARCHAR(100) NOT NULL,
  "state" VARCHAR(100) DEFAULT NULL,
  "zip" VARCHAR(20) DEFAULT NULL,
  "phone" VARCHAR(50) NOT NULL,
  "email" VARCHAR(255) DEFAULT NULL,
  "website" VARCHAR(255) DEFAULT NULL,
  "latitude" NUMERIC(10, 8) NOT NULL,
  "longitude" NUMERIC(11, 8) NOT NULL,
  "star_rating" SMALLINT DEFAULT NULL,
  "check_in_time" TIME,
  "check_out_time" TIME,
  "main_photo" VARCHAR(255) DEFAULT NULL,
  "other_photos" TEXT,
  "amenities_json" TEXT,
  "status" TEXT CHECK ("status" IN ('active','inactive','pending_approval','rejected')) NOT NULL DEFAULT 'pending_approval',
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_hotel_rooms" (
  "room_id" SERIAL PRIMARY KEY,
  "hotel_id" INTEGER NOT NULL,
  "room_type_en" VARCHAR(255) NOT NULL,
  "room_type_bn" VARCHAR(255) DEFAULT NULL,
  "description" TEXT,
  "base_price_per_night" NUMERIC(10, 2) NOT NULL,
  "max_occupancy" INTEGER NOT NULL DEFAULT 1,
  "total_rooms_available" INTEGER DEFAULT NULL,
  "current_available_rooms" INTEGER DEFAULT NULL,
  "main_photo" VARCHAR(255) DEFAULT NULL,
  "other_photos" TEXT,
  "amenities_json" TEXT,
  "is_active" SMALLINT NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_house_rentals" (
  "rental_id" SERIAL PRIMARY KEY,
  "owner_user_id" INTEGER NOT NULL,
  "property_type" VARCHAR(100) NOT NULL,
  "address" VARCHAR(255) NOT NULL,
  "city" VARCHAR(100) NOT NULL,
  "area" VARCHAR(100) DEFAULT NULL,
  "latitude" NUMERIC(10, 8) NOT NULL,
  "longitude" NUMERIC(11, 8) NOT NULL,
  "rent_amount" NUMERIC(10, 2) NOT NULL,
  "deposit_amount" NUMERIC(10, 2) DEFAULT NULL,
  "bedrooms" INTEGER DEFAULT NULL,
  "bathrooms" INTEGER DEFAULT NULL,
  "square_feet" INTEGER DEFAULT NULL,
  "description" TEXT,
  "main_photo" VARCHAR(255) DEFAULT NULL,
  "other_photos" TEXT,
  "availability_date" DATE,
  "status" TEXT CHECK ("status" IN ('available','rented','pending_approval','rejected')) NOT NULL DEFAULT 'pending_approval',
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_house_sales" (
  "sale_id" SERIAL PRIMARY KEY,
  "owner_user_id" INTEGER NOT NULL,
  "property_type" VARCHAR(100) NOT NULL,
  "address" VARCHAR(255) NOT NULL,
  "city" VARCHAR(100) NOT NULL,
  "area" VARCHAR(100) DEFAULT NULL,
  "latitude" NUMERIC(10, 8) NOT NULL,
  "longitude" NUMERIC(11, 8) NOT NULL,
  "selling_price" NUMERIC(15, 2) NOT NULL,
  "bedrooms" INTEGER DEFAULT NULL,
  "bathrooms" INTEGER DEFAULT NULL,
  "square_feet" INTEGER DEFAULT NULL,
  "land_area_sqft" NUMERIC(10, 2) DEFAULT NULL,
  "description" TEXT,
  "main_photo" VARCHAR(255) DEFAULT NULL,
  "other_photos" TEXT,
  "status" TEXT CHECK ("status" IN ('available','sold','pending_approval','rejected')) NOT NULL DEFAULT 'pending_approval',
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_kyc_verifications" (
  "kyc_id" SERIAL PRIMARY KEY,
  "cust_id" INTEGER NOT NULL,
  "nid_number" VARCHAR(50) NOT NULL,
  "nid_front" VARCHAR(255) NOT NULL,
  "nid_back" VARCHAR(255) DEFAULT NULL,
  "face_capture" VARCHAR(255) NOT NULL,
  "gps_location" VARCHAR(100) DEFAULT NULL,
  "status" TEXT CHECK ("status" IN ('pending','approved','rejected')) DEFAULT 'pending',
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_language" (
  "lang_id" SERIAL PRIMARY KEY,
  "lang_name" VARCHAR(255) NOT NULL,
  "lang_value" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_menu_categories" (
  "menu_category_id" SERIAL PRIMARY KEY,
  "restaurant_id" INTEGER NOT NULL,
  "category_name_en" VARCHAR(255) NOT NULL,
  "category_name_bn" VARCHAR(255) DEFAULT NULL,
  "display_order" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "tbl_menu_items" (
  "item_id" SERIAL PRIMARY KEY,
  "restaurant_id" INTEGER NOT NULL,
  "menu_category_id" INTEGER DEFAULT NULL,
  "item_name_en" VARCHAR(255) NOT NULL,
  "item_name_bn" VARCHAR(255) DEFAULT NULL,
  "description_en" TEXT,
  "description_bn" TEXT,
  "price" NUMERIC(10, 2) NOT NULL,
  "is_available" SMALLINT NOT NULL DEFAULT 1,
  "photo" VARCHAR(255) DEFAULT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_mid_category" (
  "mcat_id" SERIAL PRIMARY KEY,
  "mcat_name" VARCHAR(255) NOT NULL,
  "tcat_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_order" (
  "id" SERIAL PRIMARY KEY,
  "cust_id" INTEGER DEFAULT NULL,
  "product_id" INTEGER NOT NULL,
  "product_name" VARCHAR(255) NOT NULL DEFAULT '',
  "size" VARCHAR(100) NOT NULL DEFAULT '',
  "color" VARCHAR(100) NOT NULL DEFAULT '',
  "quantity" INTEGER NOT NULL CHECK (quantity>0),
  "unit_price" NUMERIC(12,2) NOT NULL DEFAULT 0,
  "payment_id" VARCHAR(255) NOT NULL DEFAULT '',
  "coupon_code" VARCHAR(100) DEFAULT NULL,
  "coupon_discount" NUMERIC(10, 2) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_page" (
  "id" SERIAL PRIMARY KEY,
  "about_title" VARCHAR(255) NOT NULL DEFAULT '',
  "about_content" TEXT NOT NULL DEFAULT '',
  "about_banner" VARCHAR(255) NOT NULL DEFAULT '',
  "about_meta_title" VARCHAR(255) NOT NULL DEFAULT '',
  "about_meta_keyword" TEXT NOT NULL DEFAULT '',
  "about_meta_description" TEXT NOT NULL DEFAULT '',
  "faq_title" VARCHAR(255) NOT NULL DEFAULT '',
  "faq_banner" VARCHAR(255) NOT NULL DEFAULT '',
  "faq_meta_title" VARCHAR(255) NOT NULL DEFAULT '',
  "faq_meta_keyword" TEXT NOT NULL DEFAULT '',
  "faq_meta_description" TEXT NOT NULL DEFAULT '',
  "blog_title" VARCHAR(255) NOT NULL DEFAULT '',
  "blog_banner" VARCHAR(255) NOT NULL DEFAULT '',
  "blog_meta_title" VARCHAR(255) NOT NULL DEFAULT '',
  "blog_meta_keyword" TEXT NOT NULL DEFAULT '',
  "blog_meta_description" TEXT NOT NULL DEFAULT '',
  "contact_title" VARCHAR(255) NOT NULL DEFAULT '',
  "contact_banner" VARCHAR(255) NOT NULL DEFAULT '',
  "contact_meta_title" VARCHAR(255) NOT NULL DEFAULT '',
  "contact_meta_keyword" TEXT NOT NULL DEFAULT '',
  "contact_meta_description" TEXT NOT NULL DEFAULT '',
  "pgallery_title" VARCHAR(255) NOT NULL DEFAULT '',
  "pgallery_banner" VARCHAR(255) NOT NULL DEFAULT '',
  "pgallery_meta_title" VARCHAR(255) NOT NULL DEFAULT '',
  "pgallery_meta_keyword" TEXT NOT NULL DEFAULT '',
  "pgallery_meta_description" TEXT NOT NULL DEFAULT '',
  "vgallery_title" VARCHAR(255) NOT NULL DEFAULT '',
  "vgallery_banner" VARCHAR(255) NOT NULL DEFAULT '',
  "vgallery_meta_title" VARCHAR(255) NOT NULL DEFAULT '',
  "vgallery_meta_keyword" TEXT NOT NULL DEFAULT '',
  "vgallery_meta_description" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS "tbl_payment" (
  "id" SERIAL PRIMARY KEY,
  "customer_id" INTEGER NOT NULL DEFAULT 0,
  "customer_name" VARCHAR(255) NOT NULL DEFAULT '',
  "customer_email" VARCHAR(255) NOT NULL DEFAULT '',
  "payment_date" VARCHAR(50) NOT NULL DEFAULT '',
  "txnid" VARCHAR(255) NOT NULL DEFAULT '',
  "paid_amount" NUMERIC(12,2) NOT NULL DEFAULT 0,
  "card_number" VARCHAR(50) DEFAULT NULL,
  "card_cvv" VARCHAR(10) DEFAULT NULL,
  "card_month" VARCHAR(10) DEFAULT NULL,
  "card_year" VARCHAR(10) DEFAULT NULL,
  "bank_transaction_info" TEXT,
  "payment_method" VARCHAR(20) NOT NULL DEFAULT '',
  "payment_status" VARCHAR(25) NOT NULL DEFAULT '',
  "shipping_status" VARCHAR(20) NOT NULL DEFAULT '',
  "payment_id" VARCHAR(255) NOT NULL DEFAULT '',
  "payment_note" TEXT,
  "ssl_payment_method" VARCHAR(100) DEFAULT NULL,
  "billing_name" VARCHAR(255) DEFAULT NULL,
  "billing_cname" VARCHAR(255) DEFAULT NULL,
  "billing_phone" VARCHAR(50) DEFAULT NULL,
  "billing_country" VARCHAR(255) DEFAULT NULL,
  "billing_address" TEXT,
  "billing_city" VARCHAR(100) DEFAULT NULL,
  "billing_state" VARCHAR(100) DEFAULT NULL,
  "billing_zip" VARCHAR(20) DEFAULT NULL,
  "shipping_name" VARCHAR(255) DEFAULT NULL,
  "shipping_cname" VARCHAR(255) DEFAULT NULL,
  "shipping_phone" VARCHAR(50) DEFAULT NULL,
  "shipping_country" VARCHAR(255) DEFAULT NULL,
  "shipping_address" TEXT,
  "shipping_city" VARCHAR(100) DEFAULT NULL,
  "shipping_state" VARCHAR(100) DEFAULT NULL,
  "shipping_zip" VARCHAR(20) DEFAULT NULL,
  "shipping_cost" NUMERIC(10, 2) DEFAULT NULL,
  "coupon_code" VARCHAR(100) DEFAULT NULL,
  "coupon_discount" NUMERIC(10, 2) DEFAULT 0.00,
  "coupon_id" INTEGER DEFAULT NULL,
  "billing_email" VARCHAR(100) DEFAULT NULL,
  "billing_street" VARCHAR(255) DEFAULT NULL,
  "shipping_street" VARCHAR(255) DEFAULT NULL,
  "shipping_email" VARCHAR(100) DEFAULT NULL,
  "customer_note" TEXT,
  "card_holder_name" VARCHAR(255) DEFAULT NULL,
  "card_security_code" VARCHAR(255) DEFAULT NULL,
  "card_expiry_month" VARCHAR(255) DEFAULT NULL,
  "card_expiry_year" VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_photo" (
  "id" SERIAL PRIMARY KEY,
  "caption" VARCHAR(255) NOT NULL,
  "photo" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_post" (
  "post_id" SERIAL PRIMARY KEY,
  "post_title" VARCHAR(255) NOT NULL,
  "post_slug" VARCHAR(255) NOT NULL,
  "post_content" TEXT NOT NULL,
  "post_date" VARCHAR(255) NOT NULL,
  "photo" VARCHAR(255) NOT NULL,
  "category_id" INTEGER NOT NULL,
  "total_view" INTEGER NOT NULL,
  "meta_title" VARCHAR(255) NOT NULL,
  "meta_keyword" TEXT NOT NULL,
  "meta_description" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_product" (
  "p_id" SERIAL PRIMARY KEY,
  "business_id" INTEGER DEFAULT NULL,
  "p_name" VARCHAR(255) NOT NULL DEFAULT '',
  "p_old_price" NUMERIC(12,2) NOT NULL DEFAULT 0,
  "p_current_price" NUMERIC(12,2) NOT NULL DEFAULT 0,
  "p_qty" INTEGER NOT NULL DEFAULT 0,
  "p_featured_photo" VARCHAR(255) NOT NULL DEFAULT '',
  "p_description" TEXT NOT NULL DEFAULT '',
  "p_short_description" TEXT NOT NULL DEFAULT '',
  "p_feature" TEXT NOT NULL DEFAULT '',
  "p_condition" TEXT NOT NULL DEFAULT '',
  "p_return_policy" TEXT NOT NULL DEFAULT '',
  "p_total_view" INTEGER NOT NULL DEFAULT 0,
  "p_is_featured" SMALLINT NOT NULL DEFAULT 0,
  "p_is_active" SMALLINT NOT NULL DEFAULT 0,
  "ecat_id" INTEGER NOT NULL DEFAULT 0,
  "p_video_link" VARCHAR(255),
  "is_top_sale" SMALLINT DEFAULT 0,
  "is_free_shipping" SMALLINT DEFAULT 0,
  "is_official" SMALLINT DEFAULT 0,
  "is_premium" SMALLINT DEFAULT 0,
  "is_overseas" SMALLINT DEFAULT 0,
  "is_max_vouchered" SMALLINT DEFAULT 0,
  "vendor_id" INTEGER DEFAULT 0,
  "allow_coin_payment" SMALLINT DEFAULT 0,
  "is_coin_buyable" SMALLINT DEFAULT 0,
  "coin_price" INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "tbl_product_color" (
  "id" SERIAL PRIMARY KEY,
  "color_id" INTEGER NOT NULL,
  "p_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_product_photo" (
  "pp_id" SERIAL PRIMARY KEY,
  "photo" VARCHAR(255) NOT NULL,
  "p_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_product_size" (
  "id" SERIAL PRIMARY KEY,
  "size_id" INTEGER NOT NULL,
  "p_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_product_variants" (
  "variant_id" SERIAL PRIMARY KEY,
  "p_id" INTEGER NOT NULL,
  "size_id" INTEGER NOT NULL,
  "color_id" INTEGER NOT NULL,
  "variant_price" NUMERIC(10, 2) NOT NULL,
  "variant_qty" INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "tbl_professionals" (
  "professional_id" SERIAL PRIMARY KEY,
  "user_id" INTEGER DEFAULT NULL,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "phone" VARCHAR(50) NOT NULL,
  "nid_number" VARCHAR(50) DEFAULT NULL,
  "nid_photo_front" VARCHAR(255) DEFAULT NULL,
  "nid_photo_back" VARCHAR(255) DEFAULT NULL,
  "license_photo" VARCHAR(255) DEFAULT NULL,
  "additional_docs" TEXT,
  "category_id" INTEGER DEFAULT NULL,
  "bio" TEXT,
  "address" VARCHAR(255) DEFAULT NULL,
  "city" VARCHAR(100) DEFAULT NULL,
  "state" VARCHAR(100) DEFAULT NULL,
  "zip" VARCHAR(20) DEFAULT NULL,
  "latitude" NUMERIC(10, 8) DEFAULT NULL,
  "longitude" NUMERIC(11, 8) DEFAULT NULL,
  "verification_status" TEXT CHECK ("verification_status" IN ('pending','approved','rejected')) NOT NULL DEFAULT 'pending',
  "documents_uploaded" SMALLINT NOT NULL DEFAULT 0,
  "profile_photo" VARCHAR(255) DEFAULT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_professional_categories" (
  "category_id" SERIAL PRIMARY KEY,
  "category_name_en" VARCHAR(255) NOT NULL,
  "category_name_bn" VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_professional_reviews" (
  "review_id" SERIAL PRIMARY KEY,
  "professional_id" INTEGER NOT NULL,
  "user_id" INTEGER NOT NULL,
  "rating" SMALLINT NOT NULL,
  "review_text" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_professional_services" (
  "service_id" SERIAL PRIMARY KEY,
  "professional_id" INTEGER NOT NULL,
  "service_name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "price" NUMERIC(10, 2) DEFAULT NULL,
  "duration_minutes" INTEGER DEFAULT NULL,
  "is_available" SMALLINT NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_project_votes" (
  "vote_id" SERIAL PRIMARY KEY,
  "project_id" INTEGER NOT NULL,
  "user_id" INTEGER NOT NULL,
  "vote_type" TEXT CHECK ("vote_type" IN ('for','against')) NOT NULL,
  "voted_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_rating" (
  "rt_id" SERIAL PRIMARY KEY,
  "p_id" INTEGER NOT NULL,
  "cust_id" INTEGER NOT NULL,
  "comment" TEXT NOT NULL,
  "rating" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_restaurants" (
  "restaurant_id" SERIAL PRIMARY KEY,
  "business_owner_id" INTEGER DEFAULT NULL,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "address" VARCHAR(255) NOT NULL,
  "city" VARCHAR(100) NOT NULL,
  "state" VARCHAR(100) DEFAULT NULL,
  "zip" VARCHAR(20) DEFAULT NULL,
  "phone" VARCHAR(50) NOT NULL,
  "email" VARCHAR(255) DEFAULT NULL,
  "latitude" NUMERIC(10, 8) NOT NULL,
  "longitude" NUMERIC(11, 8) NOT NULL,
  "opening_time" TIME,
  "closing_time" TIME,
  "is_open" SMALLINT NOT NULL DEFAULT 1,
  "status" TEXT CHECK ("status" IN ('pending','approved','rejected')) NOT NULL DEFAULT 'pending',
  "logo" VARCHAR(255) DEFAULT NULL,
  "cover_photo" VARCHAR(255) DEFAULT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_review" (
  "review_id" SERIAL PRIMARY KEY,
  "cust_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "rating" INTEGER NOT NULL,
  "review_text" TEXT NOT NULL,
  "review_date" TIMESTAMPTZ NOT NULL,
  "status" VARCHAR(20) NOT NULL DEFAULT 'Pending',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_review_image" (
  "image_id" SERIAL PRIMARY KEY,
  "review_id" INTEGER NOT NULL,
  "image_path" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_service" (
  "id" SERIAL PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "content" TEXT NOT NULL,
  "photo" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_settings" (
  "id" SERIAL PRIMARY KEY,
  "logo" TEXT NOT NULL DEFAULT '',
  "favicon" TEXT NOT NULL DEFAULT '',
  "footer_about" TEXT NOT NULL DEFAULT '',
  "footer_copyright" TEXT NOT NULL DEFAULT '',
  "contact_address" TEXT NOT NULL DEFAULT '',
  "contact_email" TEXT NOT NULL DEFAULT '',
  "contact_phone" TEXT NOT NULL DEFAULT '',
  "contact_fax" TEXT NOT NULL DEFAULT '',
  "contact_map_iframe" TEXT NOT NULL DEFAULT '',
  "receive_email" TEXT NOT NULL DEFAULT '',
  "receive_email_subject" TEXT NOT NULL DEFAULT '',
  "receive_email_thank_you_message" TEXT NOT NULL DEFAULT '',
  "forget_password_message" TEXT NOT NULL DEFAULT '',
  "total_recent_post_footer" INTEGER NOT NULL DEFAULT 0,
  "total_popular_post_footer" INTEGER NOT NULL DEFAULT 0,
  "total_recent_post_sidebar" INTEGER NOT NULL DEFAULT 0,
  "total_popular_post_sidebar" INTEGER NOT NULL DEFAULT 0,
  "total_featured_product_home" INTEGER NOT NULL DEFAULT 0,
  "total_latest_product_home" INTEGER NOT NULL DEFAULT 0,
  "total_popular_product_home" INTEGER NOT NULL DEFAULT 0,
  "meta_title_home" TEXT NOT NULL DEFAULT '',
  "meta_keyword_home" TEXT NOT NULL DEFAULT '',
  "meta_description_home" TEXT NOT NULL DEFAULT '',
  "google_client_id" VARCHAR(255) DEFAULT NULL,
  "facebook_app_id" VARCHAR(255) DEFAULT NULL,
  "twilio_account_sid" VARCHAR(255) DEFAULT NULL,
  "twilio_auth_token" VARCHAR(255) DEFAULT NULL,
  "twilio_phone_number" VARCHAR(255) DEFAULT NULL,
  "smtp_host" VARCHAR(255) DEFAULT NULL,
  "smtp_username" VARCHAR(255) DEFAULT NULL,
  "smtp_password" VARCHAR(255) DEFAULT NULL,
  "smtp_encryption" VARCHAR(50) DEFAULT 'NONE',
  "smtp_port" INTEGER DEFAULT 587,
  "smtp_from_email" VARCHAR(255) DEFAULT 'no-reply@yourdomain.com',
  "smtp_from_name" VARCHAR(255) DEFAULT 'Your Store',
  "banner_login" TEXT NOT NULL DEFAULT '',
  "banner_registration" TEXT NOT NULL DEFAULT '',
  "banner_forget_password" TEXT NOT NULL DEFAULT '',
  "banner_reset_password" TEXT NOT NULL DEFAULT '',
  "banner_search" TEXT NOT NULL DEFAULT '',
  "banner_cart" TEXT NOT NULL DEFAULT '',
  "banner_checkout" TEXT NOT NULL DEFAULT '',
  "banner_product_category" TEXT NOT NULL DEFAULT '',
  "banner_blog" TEXT NOT NULL DEFAULT '',
  "cta_title" TEXT NOT NULL DEFAULT '',
  "cta_content" TEXT NOT NULL DEFAULT '',
  "cta_read_more_text" TEXT NOT NULL DEFAULT '',
  "cta_read_more_url" TEXT NOT NULL DEFAULT '',
  "cta_photo" TEXT NOT NULL DEFAULT '',
  "featured_product_title" TEXT NOT NULL DEFAULT '',
  "featured_product_subtitle" TEXT NOT NULL DEFAULT '',
  "latest_product_title" TEXT NOT NULL DEFAULT '',
  "latest_product_subtitle" TEXT NOT NULL DEFAULT '',
  "popular_product_title" TEXT NOT NULL DEFAULT '',
  "popular_product_subtitle" TEXT NOT NULL DEFAULT '',
  "testimonial_title" TEXT NOT NULL DEFAULT '',
  "testimonial_subtitle" TEXT NOT NULL DEFAULT '',
  "testimonial_photo" TEXT NOT NULL DEFAULT '',
  "blog_title" TEXT NOT NULL DEFAULT '',
  "blog_subtitle" TEXT NOT NULL DEFAULT '',
  "newsletter_text" TEXT NOT NULL DEFAULT '',
  "paypal_email" TEXT NOT NULL DEFAULT '',
  "stripe_public_key" TEXT NOT NULL DEFAULT '',
  "stripe_secret_key" TEXT NOT NULL DEFAULT '',
  "bank_detail" TEXT NOT NULL DEFAULT '',
  "before_head" TEXT NOT NULL DEFAULT '',
  "after_body" TEXT NOT NULL DEFAULT '',
  "before_body" TEXT NOT NULL DEFAULT '',
  "home_service_on_off" INTEGER NOT NULL DEFAULT 0,
  "home_welcome_on_off" INTEGER NOT NULL DEFAULT 0,
  "home_featured_product_on_off" INTEGER NOT NULL DEFAULT 0,
  "home_latest_product_on_off" INTEGER NOT NULL DEFAULT 0,
  "home_popular_product_on_off" INTEGER NOT NULL DEFAULT 0,
  "home_testimonial_on_off" INTEGER NOT NULL DEFAULT 0,
  "home_blog_on_off" INTEGER NOT NULL DEFAULT 0,
  "newsletter_on_off" INTEGER NOT NULL DEFAULT 0,
  "ads_above_welcome_on_off" SMALLINT NOT NULL DEFAULT 0,
  "ads_above_featured_product_on_off" SMALLINT NOT NULL DEFAULT 0,
  "ads_above_latest_product_on_off" SMALLINT NOT NULL DEFAULT 0,
  "ads_above_popular_product_on_off" SMALLINT NOT NULL DEFAULT 0,
  "ads_above_testimonial_on_off" SMALLINT NOT NULL DEFAULT 0,
  "ads_category_sidebar_on_off" SMALLINT NOT NULL DEFAULT 0,
  "sslcz_store_id" VARCHAR(255) NOT NULL DEFAULT '',
  "sslcz_store_pass" VARCHAR(255) NOT NULL DEFAULT '',
  "sslcz_mode" TEXT CHECK ("sslcz_mode" IN ('sandbox','live')) NOT NULL DEFAULT 'sandbox',
  "payment_methods" VARCHAR(255) NOT NULL DEFAULT 'Cash on Delivery',
  "review_feature_on_off" SMALLINT DEFAULT 1,
  "estimated_delivery_time_local" VARCHAR(255) DEFAULT '3-5 days',
  "estimated_delivery_time_international" VARCHAR(255) DEFAULT '10-20 days',
  "gemini_api_key" VARCHAR(255),
  "flash_sale_end_time" TIMESTAMPTZ DEFAULT NULL,
  "free_delivery_threshold_qty" INTEGER DEFAULT 5,
  "product_voucher_code" VARCHAR(50) DEFAULT 'SAVE10',
  "product_voucher_discount" NUMERIC(10, 2) DEFAULT 10.00,
  "email_method" VARCHAR(50) NOT NULL DEFAULT 'smtp',
  "BASE_URL" TEXT NOT NULL DEFAULT '',
  "paypal_client_id" VARCHAR(50) NOT NULL DEFAULT '',
  "paypal_secret" TEXT NOT NULL DEFAULT '',
  "paypal_sandbox_mode" TEXT NOT NULL DEFAULT '',
  "cod_enabled" SMALLINT NOT NULL DEFAULT 0,
  "facebook_app_secret" VARCHAR(255) DEFAULT NULL,
  "google_client_secret" VARCHAR(255) DEFAULT NULL,
  "home_slider_on_off" SMALLINT DEFAULT 1,
  "home_features_on_off" SMALLINT DEFAULT 1,
  "home_map_on_off" SMALLINT NOT NULL DEFAULT 1,
  "home_newsletter_on_off" SMALLINT NOT NULL DEFAULT 1,
  "home_brand_on_off" SMALLINT NOT NULL DEFAULT 1,
  "home_category_on_off" SMALLINT NOT NULL DEFAULT 1,
  "home_slider_order" INTEGER NOT NULL DEFAULT 1,
  "home_features_order" INTEGER NOT NULL DEFAULT 2,
  "home_category_order" INTEGER NOT NULL DEFAULT 3,
  "home_flash_order" INTEGER NOT NULL DEFAULT 4,
  "home_featured_product_order" INTEGER NOT NULL DEFAULT 5,
  "home_latest_product_order" INTEGER NOT NULL DEFAULT 6,
  "home_popular_product_order" INTEGER NOT NULL DEFAULT 7,
  "bg_color_categories" VARCHAR(20) DEFAULT '#ffffff',
  "bg_color_latest_products" VARCHAR(20) DEFAULT '#ffffff',
  "show_scroll_top_btn" SMALLINT DEFAULT 0,
  "slider_side_banner_img" VARCHAR(255) DEFAULT 'side-banner.jpg',
  "slider_side_banner_text" TEXT,
  "extra_footer_section_enable" SMALLINT DEFAULT 1,
  "home_sticky_nav_on_off" SMALLINT NOT NULL DEFAULT 1,
  "home_sticky_nav_order" INTEGER NOT NULL DEFAULT 8,
  "multi_vendor_active" SMALLINT DEFAULT 1,
  "coin_system_active" SMALLINT DEFAULT 1,
  "sticky_header_mobile" SMALLINT DEFAULT 1,
  "sticky_header_desktop" SMALLINT DEFAULT 1,
  "multi_vendor_on_off" SMALLINT DEFAULT 0,
  "coin_payment_system_on_off" SMALLINT DEFAULT 0,
  "chat_system_on_off" SMALLINT DEFAULT 1,
  "coin_payment_on_off" SMALLINT DEFAULT 0,
  "desktop_advanced_layout_on_off" SMALLINT DEFAULT 1,
  "hide_banner_desktop" SMALLINT NOT NULL DEFAULT 0,
  "hide_banner_mobile" SMALLINT NOT NULL DEFAULT 0,
  "hide_free_delivery_desktop" SMALLINT NOT NULL DEFAULT 0,
  "hide_free_delivery_mobile" SMALLINT NOT NULL DEFAULT 0,
  "bg_color_featured_products" VARCHAR(255) NOT NULL DEFAULT '#ffffff',
  "featured_product_count" INTEGER NOT NULL DEFAULT 8
);

CREATE TABLE IF NOT EXISTS "tbl_shipping_cost" (
  "shipping_cost_id" SERIAL PRIMARY KEY,
  "country_id" INTEGER NOT NULL,
  "amount" VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_shipping_cost_all" (
  "sca_id" SERIAL PRIMARY KEY,
  "amount" VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_size" (
  "size_id" SERIAL PRIMARY KEY,
  "size_name" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_slider" (
  "id" SERIAL PRIMARY KEY,
  "photo" VARCHAR(255) NOT NULL,
  "heading" VARCHAR(255) DEFAULT NULL,
  "content" TEXT,
  "button_text" VARCHAR(255) DEFAULT NULL,
  "button_url" VARCHAR(255) DEFAULT NULL,
  "position" VARCHAR(50) DEFAULT NULL,
  "slide_order" INT DEFAULT 1,
  "is_active" SMALLINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "tbl_social" (
  "id" SERIAL PRIMARY KEY,
  "social_name" VARCHAR(100) NOT NULL,
  "social_url" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "tbl_subscriber" (
  "subs_id" SERIAL PRIMARY KEY,
  "subs_email" VARCHAR(255) NOT NULL,
  "subs_date" VARCHAR(255) NOT NULL,
  "subs_hash" VARCHAR(255) NOT NULL,
  "subs_active" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_top_category" (
  "tcat_id" SERIAL PRIMARY KEY,
  "tcat_name" VARCHAR(255) NOT NULL,
  "show_on_menu" SMALLINT NOT NULL DEFAULT 0,
  "tcat_order" INTEGER NOT NULL DEFAULT 1,
  "photo" VARCHAR(255) NOT NULL DEFAULT 'placeholder.svg'
);

CREATE TABLE IF NOT EXISTS "tbl_transport_bookings" (
  "booking_id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "driver_id" INTEGER DEFAULT NULL,
  "vehicle_type" TEXT CHECK ("vehicle_type" IN ('rickshaw','cng','bike','car')) NOT NULL,
  "pickup_latitude" NUMERIC(10, 8) NOT NULL,
  "pickup_longitude" NUMERIC(11, 8) NOT NULL,
  "dropoff_latitude" NUMERIC(10, 8) NOT NULL,
  "dropoff_longitude" NUMERIC(11, 8) NOT NULL,
  "pickup_address" TEXT NOT NULL,
  "dropoff_address" TEXT NOT NULL,
  "estimated_fare" NUMERIC(10, 2) DEFAULT NULL,
  "actual_fare" NUMERIC(10, 2) DEFAULT NULL,
  "distance_km" NUMERIC(10, 2) DEFAULT NULL,
  "status" TEXT CHECK ("status" IN ('pending','accepted','started','completed','cancelled')) NOT NULL DEFAULT 'pending',
  "payment_status" TEXT CHECK ("payment_status" IN ('unpaid','paid','refunded')) NOT NULL DEFAULT 'unpaid',
  "payment_method" VARCHAR(50) DEFAULT NULL,
  "booked_at" TIMESTAMPTZ DEFAULT NOW(),
  "accepted_at" TIMESTAMPTZ DEFAULT NULL,
  "started_at" TIMESTAMPTZ DEFAULT NULL,
  "completed_at" TIMESTAMPTZ DEFAULT NULL,
  "cancelled_at" TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "tbl_travel_agencies" (
  "agency_id" SERIAL PRIMARY KEY,
  "owner_user_id" INTEGER NOT NULL,
  "agency_name" VARCHAR(255) NOT NULL,
  "contact_email" VARCHAR(255) NOT NULL,
  "contact_phone" VARCHAR(50) NOT NULL,
  "address" VARCHAR(255) DEFAULT NULL,
  "description" TEXT,
  "logo" VARCHAR(255) DEFAULT NULL,
  "verification_status" TEXT CHECK ("verification_status" IN ('pending','approved','rejected')) NOT NULL DEFAULT 'pending',
  "is_active" SMALLINT NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_travel_bookings" (
  "booking_id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "agency_id" INTEGER DEFAULT NULL,
  "booking_type" TEXT CHECK ("booking_type" IN ('hotel','flight','bus','train','package')) NOT NULL,
  "service_provider" VARCHAR(255) DEFAULT NULL,
  "destination" VARCHAR(255) NOT NULL,
  "check_in_date" DATE,
  "check_out_date" DATE,
  "departure_date" DATE,
  "return_date" DATE,
  "total_passengers" INTEGER NOT NULL DEFAULT 1,
  "total_amount" NUMERIC(10, 2) NOT NULL,
  "payment_status" TEXT CHECK ("payment_status" IN ('pending','paid','refunded')) NOT NULL DEFAULT 'pending',
  "booking_status" TEXT CHECK ("booking_status" IN ('pending','confirmed','cancelled','completed')) NOT NULL DEFAULT 'pending',
  "booking_details_json" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_used_products" (
  "used_product_id" SERIAL PRIMARY KEY,
  "seller_user_id" INTEGER NOT NULL,
  "product_name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "price" NUMERIC(10, 2) NOT NULL,
  "condition" TEXT CHECK ("condition" IN ('new_like','good','fair','used')) NOT NULL DEFAULT 'good',
  "category_id" INTEGER DEFAULT NULL,
  "location_address" VARCHAR(255) DEFAULT NULL,
  "latitude" NUMERIC(10, 8) DEFAULT NULL,
  "longitude" NUMERIC(11, 8) DEFAULT NULL,
  "main_photo" VARCHAR(255) DEFAULT NULL,
  "other_photos" TEXT,
  "status" TEXT CHECK ("status" IN ('active','sold','pending_approval','rejected')) NOT NULL DEFAULT 'pending_approval',
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_user" (
  "id" SERIAL PRIMARY KEY,
  "full_name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "phone" VARCHAR(50) NOT NULL,
  "photo" VARCHAR(255) NOT NULL DEFAULT 'default.png',
  "role" VARCHAR(50) NOT NULL DEFAULT 'User',
  "password" VARCHAR(255) NOT NULL,
  "status" VARCHAR(50) NOT NULL DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS "tbl_vehicles" (
  "vehicle_id" SERIAL PRIMARY KEY,
  "driver_id" INTEGER NOT NULL,
  "make" VARCHAR(100) DEFAULT NULL,
  "model" VARCHAR(100) DEFAULT NULL,
  "license_plate" VARCHAR(50) NOT NULL,
  "color" VARCHAR(50) DEFAULT NULL,
  "photo" VARCHAR(255) DEFAULT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_vouchers" (
  "voucher_id" SERIAL PRIMARY KEY,
  "business_id" INTEGER DEFAULT NULL,
  "shop_id" INTEGER DEFAULT NULL,
  "voucher_code" VARCHAR(50) NOT NULL,
  "voucher_name" VARCHAR(255) NOT NULL,
  "voucher_value" NUMERIC(10, 2) NOT NULL,
  "min_purchase_amount" NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  "usage_limit" INTEGER NOT NULL DEFAULT 1,
  "used_count" INTEGER NOT NULL DEFAULT 0,
  "issue_date" TIMESTAMPTZ NOT NULL,
  "expiry_date" TIMESTAMPTZ NOT NULL,
  "status" TEXT CHECK ("status" IN ('active','inactive','expired')) NOT NULL DEFAULT 'active',
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tbl_wishlist" (
  "wishlist_id" SERIAL PRIMARY KEY,
  "cust_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "added_date" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

INSERT INTO "tbl_language" ("lang_id", "lang_name", "lang_value")
VALUES (1, 'Currency', 'BDT  '),
(2, 'Search Product', 'Search Product'),
(3, 'Search', 'Search'),
(4, 'Submit', 'Submit'),
(5, 'Update', 'Update'),
(6, 'Read More', 'Read More'),
(7, 'Serial', 'Serial'),
(8, 'Photo', 'Photo'),
(9, 'Login', 'Login'),
(10, 'Customer Login', 'Customer Login'),
(11, 'Click here to login', 'Click here to login'),
(12, 'Back to Login Page', 'Back to Login Page'),
(13, 'Logged in as', 'Logged in as'),
(14, 'Logout', 'Logout'),
(15, 'Register', 'Register'),
(16, 'Customer Registration', 'Customer Registration'),
(17, 'Registration Successful', 'Registration Successful'),
(18, 'Cart', 'Cart'),
(19, 'View Cart', 'View Cart'),
(20, 'Update Cart', 'Update Cart'),
(21, 'Back to Cart', 'Back to Cart'),
(22, 'Checkout', 'Checkout'),
(23, 'Proceed to Checkout', 'Proceed to Checkout'),
(24, 'Orders', 'Orders'),
(25, 'Order History', 'Order History'),
(26, 'Order Details', 'Order Details'),
(27, 'Payment Date and Time', 'Payment Date and Time'),
(28, 'Transaction ID', 'Transaction ID'),
(29, 'Paid Amount', 'Paid Amount'),
(30, 'Payment Status', 'Payment Status'),
(31, 'Payment Method', 'Payment Method'),
(32, 'Payment ID', 'Payment ID'),
(33, 'Payment Section', 'Payment Section'),
(34, 'Select Payment Method', 'Select Payment Method'),
(35, 'Select a Method', 'Select a Method'),
(36, 'PayPal', 'PayPal'),
(37, 'Stripe', 'Stripe'),
(38, 'Bank Deposit', 'Bank Deposit'),
(39, 'Card Number', 'Card Number'),
(40, 'CVV', 'CVV'),
(41, 'Month', 'Month'),
(42, 'Year', 'Year'),
(43, 'Send to this Details', 'Send to this Details'),
(44, 'Transaction Information', 'Transaction Information'),
(45, 'Include transaction id and other information correctly', 'Include transaction id and other information correctly'),
(46, 'Pay Now', 'Pay Now'),
(47, 'Product Name', 'Product Name'),
(48, 'Product Details', 'Product Details'),
(49, 'Categories', 'Categories'),
(50, 'Category:', 'Category:'),
(51, 'All Products Under', 'All Products Under'),
(52, 'Select Size', 'Select Size'),
(53, 'Select Color', 'Select Color'),
(54, 'Product Price', 'Product Price'),
(55, 'Quantity', 'Quantity'),
(56, 'Out of Stock', 'Out of Stock'),
(57, 'Share This', 'Share This'),
(58, 'Share This Product', 'Share This Product'),
(59, 'Product Description', 'Product Description'),
(60, 'Features', 'Features'),
(61, 'Conditions', 'Conditions'),
(62, 'Return Policy', 'Return Policy'),
(63, 'Reviews', 'Reviews'),
(64, 'Review', 'Review'),
(65, 'Give a Review', 'Give a Review'),
(66, 'Write your comment (Optional)', 'Write your comment (Optional)'),
(67, 'Submit Review', 'Submit Review'),
(68, 'You already have given a rating!', 'You already have given a rating!'),
(69, 'You must have to login to give a review', 'You must have to login to give a review'),
(70, 'No description found', 'No description found'),
(71, 'No feature found', 'No feature found'),
(72, 'No condition found', 'No condition found'),
(73, 'No return policy found', 'No return policy found'),
(74, 'Review not found', 'Review not found'),
(75, 'Customer Name', 'Customer Name'),
(76, 'Comment', 'Comment'),
(77, 'Comments', 'Comments'),
(78, 'Rating', 'Rating'),
(79, 'Previous', 'Previous'),
(80, 'Next', 'Next'),
(81, 'Sub Total', 'Sub Total'),
(82, 'Total', 'Total'),
(83, 'Action', 'Action'),
(84, 'Shipping Cost', 'Shipping Cost'),
(85, 'Continue Shopping', 'Continue Shopping'),
(86, 'Update Billing Address', 'Update Billing Address'),
(87, 'Update Shipping Address', 'Update Shipping Address'),
(88, 'Update Billing and Shipping Info', 'Update Billing and Shipping Info'),
(89, 'Dashboard', 'Dashboard'),
(90, 'Welcome to the Dashboard', 'Welcome to the Dashboard'),
(91, 'Back to Dashboard', 'Back to Dashboard'),
(92, 'Subscribe', 'Subscribe'),
(93, 'Subscribe To Our Newsletter', 'Subscribe To Our Newsletter'),
(94, 'Email Address', 'Email Address'),
(95, 'Enter Your Email Address', 'Enter Your Email Address'),
(96, 'Password', 'Password'),
(97, 'Forget Password', 'Forget Password'),
(98, 'Retype Password', 'Retype Password'),
(99, 'Update Password', 'Update Password'),
(100, 'New Password', 'New Password'),
(101, 'Retype New Password', 'Retype New Password'),
(102, 'Full Name', 'Full Name'),
(103, 'Company Name', 'Company Name'),
(104, 'Phone Number', 'Phone Number'),
(105, 'Address', 'Address'),
(106, 'Country', 'Country'),
(107, 'City', 'City'),
(108, 'State', 'State'),
(109, 'Zip Code', 'Zip Code'),
(110, 'About Us', 'About Us'),
(111, 'Featured Posts', 'Featured Posts'),
(112, 'Popular Posts', 'Popular Posts'),
(113, 'Recent Posts', 'Recent Posts'),
(114, 'Contact Information', 'Contact Information'),
(115, 'Contact Form', 'Contact Form'),
(116, 'Our Office', 'Our Office'),
(117, 'Update Profile', 'Update Profile'),
(118, 'Send Message', 'Send Message'),
(119, 'Message', 'Message'),
(120, 'Find Us On Map', 'Find Us On Map'),
(121, 'Congratulation! Payment is successful.', 'Congratulation! Payment is successful.'),
(122, 'Billing and Shipping Information is updated successfully.', 'Billing and Shipping Information is updated successfully.'),
(123, 'Customer Name can not be empty.', 'Customer Name can not be empty.'),
(124, 'Phone Number can not be empty.', 'Phone Number can not be empty.'),
(125, 'Address can not be empty.', 'Address can not be empty.'),
(126, 'You must have to select a country.', 'You must have to select a country.'),
(127, 'City can not be empty.', 'City can not be empty.'),
(128, 'State can not be empty.', 'State can not be empty.'),
(129, 'Zip Code can not be empty.', 'Zip Code can not be empty.'),
(130, 'Profile Information is updated successfully.', 'Profile Information is updated successfully.'),
(131, 'Email Address can not be empty', 'Email Address can not be empty'),
(132, 'Email and/or Password can not be empty.', 'Email and/or Password can not be empty.'),
(133, 'Email Address does not match.', 'Email Address does not match.'),
(134, 'Email address must be valid.', 'Email address must be valid.'),
(135, 'You email address is not found in our system.', 'You email address is not found in our system.'),
(136, 'Please check your email and confirm your subscription.', 'Please check your email and confirm your subscription.'),
(137, 'Your email is verified successfully. You can now login to our website.', 'Your email is verified successfully. You can now login to our website.'),
(138, 'Password can not be empty.', 'Password can not be empty.'),
(139, 'Passwords do not match.', 'Passwords do not match.'),
(140, 'Please enter new and retype passwords.', 'Please enter new and retype passwords.'),
(141, 'Password is updated successfully.', 'Password is updated successfully.'),
(142, 'To reset your password, please click on the link below.', 'To reset your password, please click on the link below.'),
(143, 'PASSWORD RESET REQUEST - YOUR WEBSITE.COM', 'PASSWORD RESET REQUEST - YOUR WEBSITE.COM'),
(144, 'The password reset email time (24 hours) has expired. Please again try to reset your password.', 'The password reset email time (24 hours) has expired. Please again try to reset your password.'),
(145, 'A confirmation link is sent to your email address. You will get the password reset information in there.', 'A confirmation link is sent to your email address. You will get the password reset information in there.'),
(146, 'Password is reset successfully. You can now login.', 'Password is reset successfully. You can now login.'),
(147, 'Email Address Already Exists', 'Email Address Already Exists.'),
(148, 'Sorry! Your account is inactive. Please contact to the administrator.', 'Sorry! Your account is inactive. Please contact to the administrator.'),
(149, 'Change Password', 'Change Password'),
(150, 'Registration Email Confirmation for YOUR WEBSITE', 'Registration Email Confirmation for YOUR WEBSITE.'),
(151, 'Thank you for your registration! Your account has been created. To active your account click on the link below:', 'Thank you for your registration! Your account has been created. To active your account click on the link below:'),
(152, 'Your registration is completed. Please check your email address to follow the process to confirm your registration.', 'Your registration is completed. Please check your email address to follow the process to confirm your registration.'),
(153, 'No Product Found', 'No Product Found'),
(154, 'Add to Cart', 'Add to Cart'),
(155, 'Related Products', 'Related Products'),
(156, 'See all related products from below', 'See all the related products from below'),
(157, 'Size', 'Size'),
(158, 'Color', 'Color'),
(159, 'Price', 'Price'),
(160, 'Please login as customer to checkout', 'Please login as customer to checkout'),
(161, 'Billing Address', 'Billing Address'),
(162, 'Shipping Address', 'Shipping Address'),
(163, 'Rating is Submitted Successfully!', 'Rating is Submitted Successfully!'),
(1, 'Currency', 'BDT  '),
(2, 'Search Product', 'Search Product'),
(3, 'Search', 'Search'),
(4, 'Submit', 'Submit'),
(5, 'Update', 'Update'),
(6, 'Read More', 'Read More'),
(7, 'Serial', 'Serial'),
(8, 'Photo', 'Photo'),
(9, 'Login', 'Login'),
(10, 'Customer Login', 'Customer Login'),
(11, 'Click here to login', 'Click here to login'),
(12, 'Back to Login Page', 'Back to Login Page'),
(13, 'Logged in as', 'Logged in as'),
(14, 'Logout', 'Logout'),
(15, 'Register', 'Register'),
(16, 'Customer Registration', 'Customer Registration'),
(17, 'Registration Successful', 'Registration Successful'),
(18, 'Cart', 'Cart'),
(19, 'View Cart', 'View Cart'),
(20, 'Update Cart', 'Update Cart'),
(21, 'Back to Cart', 'Back to Cart'),
(22, 'Checkout', 'Checkout'),
(23, 'Proceed to Checkout', 'Proceed to Checkout'),
(24, 'Orders', 'Orders'),
(25, 'Order History', 'Order History'),
(26, 'Order Details', 'Order Details'),
(27, 'Payment Date and Time', 'Payment Date and Time'),
(28, 'Transaction ID', 'Transaction ID'),
(29, 'Paid Amount', 'Paid Amount'),
(30, 'Payment Status', 'Payment Status'),
(31, 'Payment Method', 'Payment Method'),
(32, 'Payment ID', 'Payment ID'),
(33, 'Payment Section', 'Payment Section'),
(34, 'Select Payment Method', 'Select Payment Method'),
(35, 'Select a Method', 'Select a Method'),
(36, 'PayPal', 'PayPal'),
(37, 'Stripe', 'Stripe'),
(38, 'Bank Deposit', 'Bank Deposit'),
(39, 'Card Number', 'Card Number'),
(40, 'CVV', 'CVV'),
(41, 'Month', 'Month'),
(42, 'Year', 'Year'),
(43, 'Send to this Details', 'Send to this Details'),
(44, 'Transaction Information', 'Transaction Information'),
(45, 'Include transaction id and other information correctly', 'Include transaction id and other information correctly'),
(46, 'Pay Now', 'Pay Now'),
(47, 'Product Name', 'Product Name'),
(48, 'Product Details', 'Product Details'),
(49, 'Categories', 'Categories'),
(50, 'Category:', 'Category:'),
(51, 'All Products Under', 'All Products Under'),
(52, 'Select Size', 'Select Size'),
(53, 'Select Color', 'Select Color'),
(54, 'Product Price', 'Product Price'),
(55, 'Quantity', 'Quantity'),
(56, 'Out of Stock', 'Out of Stock'),
(57, 'Share This', 'Share This'),
(58, 'Share This Product', 'Share This Product'),
(59, 'Product Description', 'Product Description'),
(60, 'Features', 'Features'),
(61, 'Conditions', 'Conditions'),
(62, 'Return Policy', 'Return Policy'),
(63, 'Reviews', 'Reviews'),
(64, 'Review', 'Review'),
(65, 'Give a Review', 'Give a Review'),
(66, 'Write your comment (Optional)', 'Write your comment (Optional)'),
(67, 'Submit Review', 'Submit Review'),
(68, 'You already have given a rating!', 'You already have given a rating!'),
(69, 'You must have to login to give a review', 'You must have to login to give a review'),
(70, 'No description found', 'No description found'),
(71, 'No feature found', 'No feature found'),
(72, 'No condition found', 'No condition found'),
(73, 'No return policy found', 'No return policy found'),
(74, 'Review not found', 'Review not found'),
(75, 'Customer Name', 'Customer Name'),
(76, 'Comment', 'Comment'),
(77, 'Comments', 'Comments'),
(78, 'Rating', 'Rating'),
(79, 'Previous', 'Previous'),
(80, 'Next', 'Next'),
(81, 'Sub Total', 'Sub Total'),
(82, 'Total', 'Total'),
(83, 'Action', 'Action'),
(84, 'Shipping Cost', 'Shipping Cost'),
(85, 'Continue Shopping', 'Continue Shopping'),
(86, 'Update Billing Address', 'Update Billing Address'),
(87, 'Update Shipping Address', 'Update Shipping Address'),
(88, 'Update Billing and Shipping Info', 'Update Billing and Shipping Info'),
(89, 'Dashboard', 'Dashboard'),
(90, 'Welcome to the Dashboard', 'Welcome to the Dashboard'),
(91, 'Back to Dashboard', 'Back to Dashboard'),
(92, 'Subscribe', 'Subscribe'),
(93, 'Subscribe To Our Newsletter', 'Subscribe To Our Newsletter'),
(94, 'Email Address', 'Email Address'),
(95, 'Enter Your Email Address', 'Enter Your Email Address'),
(96, 'Password', 'Password'),
(97, 'Forget Password', 'Forget Password'),
(98, 'Retype Password', 'Retype Password'),
(99, 'Update Password', 'Update Password'),
(100, 'New Password', 'New Password'),
(101, 'Retype New Password', 'Retype New Password'),
(102, 'Full Name', 'Full Name'),
(103, 'Company Name', 'Company Name'),
(104, 'Phone Number', 'Phone Number'),
(105, 'Address', 'Address'),
(106, 'Country', 'Country'),
(107, 'City', 'City'),
(108, 'State', 'State'),
(109, 'Zip Code', 'Zip Code'),
(110, 'About Us', 'About Us'),
(111, 'Featured Posts', 'Featured Posts'),
(112, 'Popular Posts', 'Popular Posts'),
(113, 'Recent Posts', 'Recent Posts'),
(114, 'Contact Information', 'Contact Information'),
(115, 'Contact Form', 'Contact Form'),
(116, 'Our Office', 'Our Office'),
(117, 'Update Profile', 'Update Profile'),
(118, 'Send Message', 'Send Message'),
(119, 'Message', 'Message'),
(120, 'Find Us On Map', 'Find Us On Map'),
(121, 'Congratulation! Payment is successful.', 'Congratulation! Payment is successful.'),
(122, 'Billing and Shipping Information is updated successfully.', 'Billing and Shipping Information is updated successfully.'),
(123, 'Customer Name can not be empty.', 'Customer Name can not be empty.'),
(124, 'Phone Number can not be empty.', 'Phone Number can not be empty.'),
(125, 'Address can not be empty.', 'Address can not be empty.'),
(126, 'You must have to select a country.', 'You must have to select a country.'),
(127, 'City can not be empty.', 'City can not be empty.'),
(128, 'State can not be empty.', 'State can not be empty.'),
(129, 'Zip Code can not be empty.', 'Zip Code can not be empty.'),
(130, 'Profile Information is updated successfully.', 'Profile Information is updated successfully.'),
(131, 'Email Address can not be empty', 'Email Address can not be empty'),
(132, 'Email and/or Password can not be empty.', 'Email and/or Password can not be empty.'),
(133, 'Email Address does not match.', 'Email Address does not match.'),
(134, 'Email address must be valid.', 'Email address must be valid.'),
(135, 'You email address is not found in our system.', 'You email address is not found in our system.'),
(136, 'Please check your email and confirm your subscription.', 'Please check your email and confirm your subscription.'),
(137, 'Your email is verified successfully. You can now login to our website.', 'Your email is verified successfully. You can now login to our website.'),
(138, 'Password can not be empty.', 'Password can not be empty.'),
(139, 'Passwords do not match.', 'Passwords do not match.'),
(140, 'Please enter new and retype passwords.', 'Please enter new and retype passwords.'),
(141, 'Password is updated successfully.', 'Password is updated successfully.'),
(142, 'To reset your password, please click on the link below.', 'To reset your password, please click on the link below.'),
(143, 'PASSWORD RESET REQUEST - YOUR WEBSITE.COM', 'PASSWORD RESET REQUEST - YOUR WEBSITE.COM'),
(144, 'The password reset email time (24 hours) has expired. Please again try to reset your password.', 'The password reset email time (24 hours) has expired. Please again try to reset your password.'),
(145, 'A confirmation link is sent to your email address. You will get the password reset information in there.', 'A confirmation link is sent to your email address. You will get the password reset information in there.'),
(146, 'Password is reset successfully. You can now login.', 'Password is reset successfully. You can now login.'),
(147, 'Email Address Already Exists', 'Email Address Already Exists.'),
(148, 'Sorry! Your account is inactive. Please contact to the administrator.', 'Sorry! Your account is inactive. Please contact to the administrator.'),
(149, 'Change Password', 'Change Password'),
(150, 'Registration Email Confirmation for YOUR WEBSITE', 'Registration Email Confirmation for YOUR WEBSITE.'),
(151, 'Thank you for your registration! Your account has been created. To active your account click on the link below:', 'Thank you for your registration! Your account has been created. To active your account click on the link below:'),
(152, 'Your registration is completed. Please check your email address to follow the process to confirm your registration.', 'Your registration is completed. Please check your email address to follow the process to confirm your registration.'),
(153, 'No Product Found', 'No Product Found'),
(154, 'Add to Cart', 'Add to Cart'),
(155, 'Related Products', 'Related Products'),
(156, 'See all related products from below', 'See all the related products from below'),
(157, 'Size', 'Size'),
(158, 'Color', 'Color'),
(159, 'Price', 'Price'),
(160, 'Please login as customer to checkout', 'Please login as customer to checkout'),
(161, 'Billing Address', 'Billing Address'),
(162, 'Shipping Address', 'Shipping Address'),
(163, 'Rating is Submitted Successfully!', 'Rating is Submitted Successfully!')
ON CONFLICT ("lang_id") DO NOTHING;
SELECT setval(pg_get_serial_sequence('tbl_language','lang_id'),(SELECT max(lang_id) FROM tbl_language));
INSERT INTO "tbl_country" ("country_id", "country_name")
VALUES (1, 'Afghanistan'),
(2, 'Albania'),
(3, 'Algeria'),
(4, 'American Samoa'),
(5, 'Andorra'),
(6, 'Angola'),
(7, 'Anguilla'),
(8, 'Antarctica'),
(9, 'Antigua and Barbuda'),
(10, 'Argentina'),
(11, 'Armenia'),
(12, 'Aruba'),
(13, 'Australia'),
(14, 'Austria'),
(15, 'Azerbaijan'),
(16, 'Bahamas'),
(17, 'Bahrain'),
(18, 'Bangladesh'),
(19, 'Barbados'),
(20, 'Belarus'),
(21, 'Belgium'),
(22, 'Belize'),
(23, 'Benin'),
(24, 'Bermuda'),
(25, 'Bhutan'),
(26, 'Bolivia'),
(27, 'Bosnia and Herzegovina'),
(28, 'Botswana'),
(29, 'Bouvet Island'),
(30, 'Brazil'),
(31, 'British Indian Ocean Territory'),
(32, 'Brunei Darussalam'),
(33, 'Bulgaria'),
(34, 'Burkina Faso'),
(35, 'Burundi'),
(36, 'Cambodia'),
(37, 'Cameroon'),
(38, 'Canada'),
(39, 'Cape Verde'),
(40, 'Cayman Islands'),
(41, 'Central African Republic'),
(42, 'Chad'),
(43, 'Chile'),
(44, 'China'),
(45, 'Christmas Island'),
(46, 'Cocos (Keeling) Islands'),
(47, 'Colombia'),
(48, 'Comoros'),
(49, 'Congo'),
(50, 'Cook Islands'),
(51, 'Costa Rica'),
(52, 'Croatia (Hrvatska)'),
(53, 'Cuba'),
(54, 'Cyprus'),
(55, 'Czech Republic'),
(56, 'Denmark'),
(57, 'Djibouti'),
(58, 'Dominica'),
(59, 'Dominican Republic'),
(60, 'East Timor'),
(61, 'Ecuador'),
(62, 'Egypt'),
(63, 'El Salvador'),
(64, 'Equatorial Guinea'),
(65, 'Eritrea'),
(66, 'Estonia'),
(67, 'Ethiopia'),
(68, 'Falkland Islands (Malvinas)'),
(69, 'Faroe Islands'),
(70, 'Fiji'),
(71, 'Finland'),
(72, 'France'),
(73, 'France, Metropolitan'),
(74, 'French Guiana'),
(75, 'French Polynesia'),
(76, 'French Southern Territories'),
(77, 'Gabon'),
(78, 'Gambia'),
(79, 'Georgia'),
(80, 'Germany'),
(81, 'Ghana'),
(82, 'Gibraltar'),
(83, 'Guernsey'),
(84, 'Greece'),
(85, 'Greenland'),
(86, 'Grenada'),
(87, 'Guadeloupe'),
(88, 'Guam'),
(89, 'Guatemala'),
(90, 'Guinea'),
(91, 'Guinea-Bissau'),
(92, 'Guyana'),
(93, 'Haiti'),
(94, 'Heard and Mc Donald Islands'),
(95, 'Honduras'),
(96, 'Hong Kong'),
(97, 'Hungary'),
(98, 'Iceland'),
(99, 'India'),
(100, 'Isle of Man'),
(101, 'Indonesia'),
(102, 'Iran (Islamic Republic of)'),
(103, 'Iraq'),
(104, 'Ireland'),
(105, 'Israel'),
(106, 'Italy'),
(107, 'Ivory Coast'),
(108, 'Jersey'),
(109, 'Jamaica'),
(110, 'Japan'),
(111, 'Jordan'),
(112, 'Kazakhstan'),
(113, 'Kenya'),
(114, 'Kiribati'),
(115, 'Korea, Democratic People''s Republic of'),
(116, 'Korea, Republic of'),
(117, 'Kosovo'),
(118, 'Kuwait'),
(119, 'Kyrgyzstan'),
(120, 'Lao People''s Democratic Republic'),
(121, 'Latvia'),
(122, 'Lebanon'),
(123, 'Lesotho'),
(124, 'Liberia'),
(125, 'Libyan Arab Jamahiriya'),
(126, 'Liechtenstein'),
(127, 'Lithuania'),
(128, 'Luxembourg'),
(129, 'Macau'),
(130, 'Macedonia'),
(131, 'Madagascar'),
(132, 'Malawi'),
(133, 'Malaysia'),
(134, 'Maldives'),
(135, 'Mali'),
(136, 'Malta'),
(137, 'Marshall Islands'),
(138, 'Martinique'),
(139, 'Mauritania'),
(140, 'Mauritius'),
(141, 'Mayotte'),
(142, 'Mexico'),
(143, 'Micronesia, Federated States of'),
(144, 'Moldova, Republic of'),
(145, 'Monaco'),
(146, 'Mongolia'),
(147, 'Montenegro'),
(148, 'Montserrat'),
(149, 'Morocco'),
(150, 'Mozambique'),
(151, 'Myanmar'),
(152, 'Namibia'),
(153, 'Nauru'),
(154, 'Nepal'),
(155, 'Netherlands'),
(156, 'Netherlands Antilles'),
(157, 'New Caledonia'),
(158, 'New Zealand'),
(159, 'Nicaragua'),
(160, 'Niger'),
(161, 'Nigeria'),
(162, 'Niue'),
(163, 'Norfolk Island'),
(164, 'Northern Mariana Islands'),
(165, 'Norway'),
(166, 'Oman'),
(167, 'Pakistan'),
(168, 'Palau'),
(169, 'Palestine'),
(170, 'Panama'),
(171, 'Papua New Guinea'),
(172, 'Paraguay'),
(173, 'Peru'),
(174, 'Philippines'),
(175, 'Pitcairn'),
(176, 'Poland'),
(177, 'Portugal'),
(178, 'Puerto Rico'),
(179, 'Qatar'),
(180, 'Reunion'),
(181, 'Romania'),
(182, 'Russian Federation'),
(183, 'Rwanda'),
(184, 'Saint Kitts and Nevis'),
(185, 'Saint Lucia'),
(186, 'Saint Vincent and the Grenadines'),
(187, 'Samoa'),
(188, 'San Marino'),
(189, 'Sao Tome and Principe'),
(190, 'Saudi Arabia'),
(191, 'Senegal'),
(192, 'Serbia'),
(193, 'Seychelles'),
(194, 'Sierra Leone'),
(195, 'Singapore'),
(196, 'Slovakia'),
(197, 'Slovenia'),
(198, 'Solomon Islands'),
(199, 'Somalia'),
(200, 'South Africa'),
(201, 'South Georgia South Sandwich Islands'),
(202, 'Spain'),
(203, 'Sri Lanka'),
(204, 'St. Helena'),
(205, 'St. Pierre and Miquelon'),
(206, 'Sudan'),
(207, 'Suriname'),
(208, 'Svalbard and Jan Mayen Islands'),
(209, 'Swaziland'),
(210, 'Sweden'),
(211, 'Switzerland'),
(212, 'Syrian Arab Republic'),
(213, 'Taiwan'),
(214, 'Tajikistan'),
(215, 'Tanzania, United Republic of'),
(216, 'Thailand'),
(217, 'Togo'),
(218, 'Tokelau'),
(219, 'Tonga'),
(220, 'Trinidad and Tobago'),
(221, 'Tunisia'),
(222, 'Turkey'),
(223, 'Turkmenistan'),
(224, 'Turks and Caicos Islands'),
(225, 'Tuvalu'),
(226, 'Uganda'),
(227, 'Ukraine'),
(228, 'United Arab Emirates'),
(229, 'United Kingdom'),
(230, 'United States'),
(231, 'United States minor outlying islands'),
(232, 'Uruguay'),
(233, 'Uzbekistan'),
(234, 'Vanuatu'),
(235, 'Vatican City State'),
(236, 'Venezuela'),
(237, 'Vietnam'),
(238, 'Virgin Islands (British)'),
(239, 'Virgin Islands (U.S.)'),
(240, 'Wallis and Futuna Islands'),
(241, 'Western Sahara'),
(242, 'Yemen'),
(243, 'Zaire'),
(244, 'Zambia'),
(245, 'Zimbabwe'),
(1, 'Afghanistan'),
(2, 'Albania'),
(3, 'Algeria'),
(4, 'American Samoa'),
(5, 'Andorra'),
(6, 'Angola'),
(7, 'Anguilla'),
(8, 'Antarctica'),
(9, 'Antigua and Barbuda'),
(10, 'Argentina'),
(11, 'Armenia'),
(12, 'Aruba'),
(13, 'Australia'),
(14, 'Austria'),
(15, 'Azerbaijan'),
(16, 'Bahamas'),
(17, 'Bahrain'),
(18, 'Bangladesh'),
(19, 'Barbados'),
(20, 'Belarus'),
(21, 'Belgium'),
(22, 'Belize'),
(23, 'Benin'),
(24, 'Bermuda'),
(25, 'Bhutan'),
(26, 'Bolivia'),
(27, 'Bosnia and Herzegovina'),
(28, 'Botswana'),
(29, 'Bouvet Island'),
(30, 'Brazil'),
(31, 'British Indian Ocean Territory'),
(32, 'Brunei Darussalam'),
(33, 'Bulgaria'),
(34, 'Burkina Faso'),
(35, 'Burundi'),
(36, 'Cambodia'),
(37, 'Cameroon'),
(38, 'Canada'),
(39, 'Cape Verde'),
(40, 'Cayman Islands'),
(41, 'Central African Republic'),
(42, 'Chad'),
(43, 'Chile'),
(44, 'China'),
(45, 'Christmas Island'),
(46, 'Cocos (Keeling) Islands'),
(47, 'Colombia'),
(48, 'Comoros'),
(49, 'Congo'),
(50, 'Cook Islands'),
(51, 'Costa Rica'),
(52, 'Croatia (Hrvatska)'),
(53, 'Cuba'),
(54, 'Cyprus'),
(55, 'Czech Republic'),
(56, 'Denmark'),
(57, 'Djibouti'),
(58, 'Dominica'),
(59, 'Dominican Republic'),
(60, 'East Timor'),
(61, 'Ecuador'),
(62, 'Egypt'),
(63, 'El Salvador'),
(64, 'Equatorial Guinea'),
(65, 'Eritrea'),
(66, 'Estonia'),
(67, 'Ethiopia'),
(68, 'Falkland Islands (Malvinas)'),
(69, 'Faroe Islands'),
(70, 'Fiji'),
(71, 'Finland'),
(72, 'France'),
(73, 'France, Metropolitan'),
(74, 'French Guiana'),
(75, 'French Polynesia'),
(76, 'French Southern Territories'),
(77, 'Gabon'),
(78, 'Gambia'),
(79, 'Georgia'),
(80, 'Germany'),
(81, 'Ghana'),
(82, 'Gibraltar'),
(83, 'Guernsey'),
(84, 'Greece'),
(85, 'Greenland'),
(86, 'Grenada'),
(87, 'Guadeloupe'),
(88, 'Guam'),
(89, 'Guatemala'),
(90, 'Guinea'),
(91, 'Guinea-Bissau'),
(92, 'Guyana'),
(93, 'Haiti'),
(94, 'Heard and Mc Donald Islands'),
(95, 'Honduras'),
(96, 'Hong Kong'),
(97, 'Hungary'),
(98, 'Iceland'),
(99, 'India'),
(100, 'Isle of Man'),
(101, 'Indonesia'),
(102, 'Iran (Islamic Republic of)'),
(103, 'Iraq'),
(104, 'Ireland'),
(105, 'Israel'),
(106, 'Italy'),
(107, 'Ivory Coast'),
(108, 'Jersey'),
(109, 'Jamaica'),
(110, 'Japan'),
(111, 'Jordan'),
(112, 'Kazakhstan'),
(113, 'Kenya'),
(114, 'Kiribati'),
(115, 'Korea, Democratic People''s Republic of'),
(116, 'Korea, Republic of'),
(117, 'Kosovo'),
(118, 'Kuwait'),
(119, 'Kyrgyzstan'),
(120, 'Lao People''s Democratic Republic'),
(121, 'Latvia'),
(122, 'Lebanon'),
(123, 'Lesotho'),
(124, 'Liberia'),
(125, 'Libyan Arab Jamahiriya'),
(126, 'Liechtenstein'),
(127, 'Lithuania'),
(128, 'Luxembourg'),
(129, 'Macau'),
(130, 'Macedonia'),
(131, 'Madagascar'),
(132, 'Malawi'),
(133, 'Malaysia'),
(134, 'Maldives'),
(135, 'Mali'),
(136, 'Malta'),
(137, 'Marshall Islands'),
(138, 'Martinique'),
(139, 'Mauritania'),
(140, 'Mauritius'),
(141, 'Mayotte'),
(142, 'Mexico'),
(143, 'Micronesia, Federated States of'),
(144, 'Moldova, Republic of'),
(145, 'Monaco'),
(146, 'Mongolia'),
(147, 'Montenegro'),
(148, 'Montserrat'),
(149, 'Morocco'),
(150, 'Mozambique'),
(151, 'Myanmar'),
(152, 'Namibia'),
(153, 'Nauru'),
(154, 'Nepal'),
(155, 'Netherlands'),
(156, 'Netherlands Antilles'),
(157, 'New Caledonia'),
(158, 'New Zealand'),
(159, 'Nicaragua'),
(160, 'Niger'),
(161, 'Nigeria'),
(162, 'Niue'),
(163, 'Norfolk Island'),
(164, 'Northern Mariana Islands'),
(165, 'Norway'),
(166, 'Oman'),
(167, 'Pakistan'),
(168, 'Palau'),
(169, 'Palestine'),
(170, 'Panama'),
(171, 'Papua New Guinea'),
(172, 'Paraguay'),
(173, 'Peru'),
(174, 'Philippines'),
(175, 'Pitcairn'),
(176, 'Poland'),
(177, 'Portugal'),
(178, 'Puerto Rico'),
(179, 'Qatar'),
(180, 'Reunion'),
(181, 'Romania'),
(182, 'Russian Federation'),
(183, 'Rwanda'),
(184, 'Saint Kitts and Nevis'),
(185, 'Saint Lucia'),
(186, 'Saint Vincent and the Grenadines'),
(187, 'Samoa'),
(188, 'San Marino'),
(189, 'Sao Tome and Principe'),
(190, 'Saudi Arabia'),
(191, 'Senegal'),
(192, 'Serbia'),
(193, 'Seychelles'),
(194, 'Sierra Leone'),
(195, 'Singapore'),
(196, 'Slovakia'),
(197, 'Slovenia'),
(198, 'Solomon Islands'),
(199, 'Somalia'),
(200, 'South Africa'),
(201, 'South Georgia South Sandwich Islands'),
(202, 'Spain'),
(203, 'Sri Lanka'),
(204, 'St. Helena'),
(205, 'St. Pierre and Miquelon'),
(206, 'Sudan'),
(207, 'Suriname'),
(208, 'Svalbard and Jan Mayen Islands'),
(209, 'Swaziland'),
(210, 'Sweden'),
(211, 'Switzerland'),
(212, 'Syrian Arab Republic'),
(213, 'Taiwan'),
(214, 'Tajikistan'),
(215, 'Tanzania, United Republic of'),
(216, 'Thailand'),
(217, 'Togo'),
(218, 'Tokelau'),
(219, 'Tonga'),
(220, 'Trinidad and Tobago'),
(221, 'Tunisia'),
(222, 'Turkey'),
(223, 'Turkmenistan'),
(224, 'Turks and Caicos Islands'),
(225, 'Tuvalu'),
(226, 'Uganda'),
(227, 'Ukraine'),
(228, 'United Arab Emirates'),
(229, 'United Kingdom'),
(230, 'United States'),
(231, 'United States minor outlying islands'),
(232, 'Uruguay'),
(233, 'Uzbekistan'),
(234, 'Vanuatu'),
(235, 'Vatican City State'),
(236, 'Venezuela'),
(237, 'Vietnam'),
(238, 'Virgin Islands (British)'),
(239, 'Virgin Islands (U.S.)'),
(240, 'Wallis and Futuna Islands'),
(241, 'Western Sahara'),
(242, 'Yemen'),
(243, 'Zaire'),
(244, 'Zambia'),
(245, 'Zimbabwe')
ON CONFLICT ("country_id") DO NOTHING;
SELECT setval(pg_get_serial_sequence('tbl_country','country_id'),(SELECT max(country_id) FROM tbl_country));
INSERT INTO "tbl_size" ("size_id", "size_name")
VALUES (1, 'XS'),
(2, 'S'),
(3, 'M'),
(4, 'L'),
(5, 'XL'),
(6, 'XXL'),
(7, '3XL'),
(8, '31'),
(9, '32'),
(10, '33'),
(11, '34'),
(12, '35'),
(13, '36'),
(14, '37'),
(15, '38'),
(16, '39'),
(17, '40'),
(18, '41'),
(19, '42'),
(20, '43'),
(21, '44'),
(22, '45'),
(23, '46'),
(24, '47'),
(25, '48'),
(26, 'Free Size'),
(27, 'One Size for All'),
(28, '10'),
(29, '12 Months'),
(30, '2T'),
(31, '3T'),
(32, '4T'),
(33, '5T'),
(34, '6 Years'),
(35, '7 Years'),
(36, '8 Years'),
(37, '10 Years'),
(38, '12 Years'),
(39, '14 Years'),
(40, '256 GB'),
(41, '128 GB'),
(42, '14 Plus'),
(43, '16 Plus'),
(44, '18 Plus'),
(45, '20 Plus'),
(46, '22 Plus'),
(47, '24 Plus')
ON CONFLICT ("size_id") DO NOTHING;
SELECT setval(pg_get_serial_sequence('tbl_size','size_id'),(SELECT max(size_id) FROM tbl_size));
INSERT INTO "tbl_color" ("color_id", "color_name")
VALUES (1, 'Red'),
(2, 'Black'),
(3, 'Blue'),
(4, 'Yellow'),
(5, 'Green'),
(6, 'White'),
(7, 'Orange'),
(8, 'Brown'),
(9, 'Tan'),
(10, 'Pink'),
(11, 'Mixed'),
(12, 'Lightblue'),
(13, 'Violet'),
(14, 'Light Purple'),
(15, 'Salmon'),
(16, 'Gold'),
(17, 'Gray'),
(18, 'Ash'),
(19, 'Maroon'),
(20, 'Silver'),
(21, 'Dark Clay'),
(22, 'Cognac'),
(23, 'Coffee'),
(24, 'Charcoal'),
(25, 'Navy'),
(26, 'Fuchsia'),
(27, 'Olive'),
(28, 'Burgundy'),
(29, 'Midnight Blue'),
(1, 'Red'),
(2, 'Black'),
(3, 'Blue'),
(4, 'Yellow'),
(5, 'Green'),
(6, 'White'),
(7, 'Orange'),
(8, 'Brown'),
(9, 'Tan'),
(10, 'Pink'),
(11, 'Mixed'),
(12, 'Lightblue'),
(13, 'Violet'),
(14, 'Light Purple'),
(15, 'Salmon'),
(16, 'Gold'),
(17, 'Gray'),
(18, 'Ash'),
(19, 'Maroon'),
(20, 'Silver'),
(21, 'Dark Clay'),
(22, 'Cognac'),
(23, 'Coffee'),
(24, 'Charcoal'),
(25, 'Navy'),
(26, 'Fuchsia'),
(27, 'Olive'),
(28, 'Burgundy'),
(29, 'Midnight Blue')
ON CONFLICT ("color_id") DO NOTHING;
SELECT setval(pg_get_serial_sequence('tbl_color','color_id'),(SELECT max(color_id) FROM tbl_color));

CREATE OR REPLACE FUNCTION rand() RETURNS double precision LANGUAGE sql AS 'SELECT random()';
ALTER TABLE tbl_product ADD COLUMN IF NOT EXISTS source_id text UNIQUE;
ALTER TABLE tbl_product ALTER COLUMN p_featured_photo SET DEFAULT 'placeholder.svg';
ALTER TABLE tbl_product ADD CONSTRAINT product_stock_nonnegative CHECK (p_qty >= 0);
ALTER TABLE tbl_product ADD CONSTRAINT product_price_nonnegative CHECK (p_current_price >= 0);
ALTER TABLE tbl_settings ADD COLUMN IF NOT EXISTS theme_color varchar(7) NOT NULL DEFAULT '#4F46E5';
ALTER TABLE tbl_settings ADD COLUMN IF NOT EXISTS currency_code varchar(3) NOT NULL DEFAULT 'BDT';
ALTER TABLE tbl_settings ADD COLUMN popup_on_off smallint NOT NULL DEFAULT 0;
ALTER TABLE tbl_settings ADD COLUMN popup_text text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN popup_link text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN popup_photo text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN sms_api_key text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN sms_sender_id text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN sms_feature_on_off smallint NOT NULL DEFAULT 0;
ALTER TABLE tbl_settings ADD COLUMN facebook_url text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN instagram_url text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN linkedin_url text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN twitter_url text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN youtube_url text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN copyright_text text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN footer_about_us text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN payment_verified_image text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_about text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_contact text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_customer_panel text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_faq text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_payment text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_photo_gallery text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_privacy text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_return_policy text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_shipping text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_team text NOT NULL DEFAULT '';
ALTER TABLE tbl_settings ADD COLUMN banner_terms text NOT NULL DEFAULT '';
ALTER TABLE tbl_product ADD COLUMN slug text UNIQUE;
ALTER TABLE tbl_top_category ADD COLUMN slug text UNIQUE;
ALTER TABLE tbl_mid_category ADD COLUMN slug text UNIQUE;
ALTER TABLE tbl_end_category ADD COLUMN slug text UNIQUE;
ALTER TABLE tbl_product_size ADD CONSTRAINT product_size_unique UNIQUE(p_id,size_id);
ALTER TABLE tbl_product_color ADD CONSTRAINT product_color_unique UNIQUE(p_id,color_id);
ALTER TABLE tbl_product_size ADD CONSTRAINT product_size_product_fk FOREIGN KEY(p_id) REFERENCES tbl_product(p_id) ON DELETE CASCADE;
ALTER TABLE tbl_product_size ADD CONSTRAINT product_size_option_fk FOREIGN KEY(size_id) REFERENCES tbl_size(size_id) ON DELETE RESTRICT;
ALTER TABLE tbl_product_color ADD CONSTRAINT product_color_product_fk FOREIGN KEY(p_id) REFERENCES tbl_product(p_id) ON DELETE CASCADE;
ALTER TABLE tbl_product_color ADD CONSTRAINT product_color_option_fk FOREIGN KEY(color_id) REFERENCES tbl_color(color_id) ON DELETE RESTRICT;
ALTER TABLE tbl_product_photo ADD CONSTRAINT product_photo_product_fk FOREIGN KEY(p_id) REFERENCES tbl_product(p_id) ON DELETE CASCADE;
ALTER TABLE tbl_mid_category ADD CONSTRAINT mid_category_parent_fk FOREIGN KEY(tcat_id) REFERENCES tbl_top_category(tcat_id) ON DELETE RESTRICT;
ALTER TABLE tbl_end_category ADD CONSTRAINT end_category_parent_fk FOREIGN KEY(mcat_id) REFERENCES tbl_mid_category(mcat_id) ON DELETE RESTRICT;
ALTER TABLE tbl_product ADD CONSTRAINT product_category_fk FOREIGN KEY(ecat_id) REFERENCES tbl_end_category(ecat_id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX storefront_payment_reference ON tbl_payment(payment_id);
CREATE INDEX storefront_order_payment ON tbl_order(payment_id);
CREATE INDEX storefront_active_products ON tbl_product(p_is_active,p_id);
CREATE UNIQUE INDEX storefront_admin_email ON tbl_user(lower(email));
CREATE UNIQUE INDEX storefront_customer_email ON tbl_customer(lower(cust_email));
CREATE UNIQUE INDEX storefront_customer_review ON tbl_review(cust_id,product_id);
ALTER TABLE tbl_review ADD CONSTRAINT storefront_review_rating CHECK (rating BETWEEN 1 AND 5);
CREATE TABLE shop_login_attempts (attempt_key text PRIMARY KEY, failures integer NOT NULL DEFAULT 0, last_attempt timestamptz NOT NULL DEFAULT now());
INSERT INTO tbl_settings(id,logo,favicon,meta_title_home,footer_copyright,featured_product_title,latest_product_title,popular_product_title,
 home_featured_product_on_off,home_latest_product_on_off,total_featured_product_home,total_latest_product_home,total_popular_product_home,
 home_map_on_off,home_newsletter_on_off,home_brand_on_off,home_slider_on_off,home_features_on_off,home_category_on_off,
 multi_vendor_active,coin_system_active,chat_system_on_off,cod_enabled,payment_methods,product_voucher_code,product_voucher_discount,
 slider_side_banner_img,extra_footer_section_enable,hide_banner_desktop,hide_banner_mobile,hide_free_delivery_desktop,hide_free_delivery_mobile)
 VALUES(1,'logo.svg','logo.svg','Your Store','All rights reserved.','Featured products','New arrivals','Popular products',
 1,1,8,12,8,0,0,0,0,0,1,0,0,0,1,'Cash on Delivery','',0,'',0,1,1,1,1);
INSERT INTO tbl_page(id,about_title,about_content,faq_title,contact_title) VALUES(1,'About our store','Welcome to our online store.','Frequently asked questions','Contact us');
INSERT INTO tbl_top_category(tcat_id,tcat_name,show_on_menu,tcat_order,photo) VALUES(1,'Shop',1,1,'placeholder.svg');
INSERT INTO tbl_mid_category(mcat_id,mcat_name,tcat_id) VALUES(1,'All products',1);
INSERT INTO tbl_end_category(ecat_id,ecat_name,mcat_id) VALUES(1,'General',1);
INSERT INTO tbl_shipping_cost_all(sca_id,amount) VALUES(1,0);
SELECT setval(pg_get_serial_sequence('tbl_user','id'),1);
SELECT setval(pg_get_serial_sequence('tbl_settings','id'),1);
SELECT setval(pg_get_serial_sequence('tbl_page','id'),1);
SELECT setval(pg_get_serial_sequence('tbl_top_category','tcat_id'),1);
SELECT setval(pg_get_serial_sequence('tbl_mid_category','mcat_id'),1);
SELECT setval(pg_get_serial_sequence('tbl_end_category','ecat_id'),1);
SELECT setval(pg_get_serial_sequence('tbl_shipping_cost_all','sca_id'),1);

INSERT INTO tbl_social(social_name,social_url) VALUES('Facebook','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Twitter','');
INSERT INTO tbl_social(social_name,social_url) VALUES('LinkedIn','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Google Plus','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Pinterest','');
INSERT INTO tbl_social(social_name,social_url) VALUES('YouTube','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Instagram','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Tumblr','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Flickr','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Reddit','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Snapchat','');
INSERT INTO tbl_social(social_name,social_url) VALUES('WhatsApp','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Quora','');
INSERT INTO tbl_social(social_name,social_url) VALUES('StumbleUpon','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Delicious','');
INSERT INTO tbl_social(social_name,social_url) VALUES('Digg','');